// <auto-generated />
using Cs2CaseOpener.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cs2CaseOpener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CaseSkin", b =>
                {
                    b.Property<string>("CasesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CasesId", "SkinsId");

                    b.HasIndex("SkinsId");

                    b.ToTable("CasesSkins", (string)null);
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Case", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketHashName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPlayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Rental")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Skin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classid")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GunType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnifeType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxFloat")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinFloat")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prices")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RarityColor")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Stattrak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Skins", (string)null);
                });

            modelBuilder.Entity("CaseSkin", b =>
                {
                    b.HasOne("Cs2CaseOpener.Models.Case", null)
                        .WithMany()
                        .HasForeignKey("CasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2CaseOpener.Models.Skin", null)
                        .WithMany()
                        .HasForeignKey("SkinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
