// <auto-generated />
using System;
using Cs2CaseOpener.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cs2CaseOpener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250223132816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CrateSkin", b =>
                {
                    b.Property<string>("CratesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CratesId", "SkinsId");

                    b.HasIndex("SkinsId");

                    b.ToTable("CrateSkins", (string)null);
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Crate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("First_Sale_Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_sale_date");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Market_Hash_Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("market_hash_name");

                    b.Property<string>("Model_Player")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_player");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool?>("Rental")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rental");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Crates");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("SkinId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("skinId");

                    b.Property<double?>("Steam_Last_24h")
                        .HasColumnType("REAL")
                        .HasColumnName("steam_last_24h");

                    b.Property<double?>("Steam_Last_30d")
                        .HasColumnType("REAL")
                        .HasColumnName("steam_last_30d");

                    b.Property<double?>("Steam_Last_7d")
                        .HasColumnType("REAL")
                        .HasColumnName("steam_last_7d");

                    b.Property<double?>("Steam_Last_90d")
                        .HasColumnType("REAL")
                        .HasColumnName("steam_last_90d");

                    b.Property<double?>("Steam_Last_Ever")
                        .HasColumnType("REAL")
                        .HasColumnName("steam_last_ever");

                    b.Property<string>("Wear_Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("wear_category");

                    b.HasKey("Id");

                    b.HasIndex("SkinId", "Wear_Category")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Rarity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Skin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PaintIndex")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("paint_index");

                    b.Property<string>("RarityId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("rarity_id");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RarityId");

                    b.ToTable("Skins");
                });

            modelBuilder.Entity("CrateSkin", b =>
                {
                    b.HasOne("Cs2CaseOpener.Models.Crate", null)
                        .WithMany()
                        .HasForeignKey("CratesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cs2CaseOpener.Models.Skin", null)
                        .WithMany()
                        .HasForeignKey("SkinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Price", b =>
                {
                    b.HasOne("Cs2CaseOpener.Models.Skin", "Skin")
                        .WithMany("Prices")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Skin", b =>
                {
                    b.HasOne("Cs2CaseOpener.Models.Rarity", "Rarity")
                        .WithMany("Skins")
                        .HasForeignKey("RarityId");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Rarity", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("Cs2CaseOpener.Models.Skin", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
